using System.Text;
using System.Text.Json;

namespace PublisherNonBlocking {

    /// <summary>
    /// Message for testing buffer saturation.
    /// </summary>
    /// <remarks>The text used here is generated through <see href="https://www.lipsum.com">Lorem Ipsum</see>.</remarks>
    public class TestMessage {

        internal static TestMessage CreateInstance() {
            var retval = new TestMessage();
            return retval;
        }

        internal byte[] GetBytes() {
            return Encoding.ASCII.GetBytes(
                JsonSerializer.Serialize(
                    this,
                    typeof(TestMessage),
                    new JsonSerializerOptions { WriteIndented = true }
                )
            );
        }

        public string Message => Message1K;

        const string Message512 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id efficitur lorem, vitae efficitur erat. Fusce eleifend non dui ut auctor. Nam et eros eget nisl venenatis semper et eu enim. Donec libero lacus, porttitor at pretium eu, molestie ac libero. Sed finibus ipsum at velit lacinia, molestie scelerisque lorem vestibulum. Ut varius ipsum sed dictum viverra. Fusce feugiat urna at suscipit consequat. Nulla facilisi. Nulla facilisi. Pellentesque condimentum lacus at metus efficitur, eget dapibus velit nam.";

        const string Message1K =
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis nisi sed ligula interdum congue. Pellentesque et ipsum sapien. Donec consectetur neque sit amet justo hendrerit, quis varius felis pharetra. Morbi ex ipsum, imperdiet at aliquam iaculis, malesuada in neque. Nunc pharetra felis at metus rutrum, sit amet laoreet enim blandit. Integer condimentum ultrices nunc. Mauris hendrerit elit sed ultrices malesuada. Phasellus libero lectus, rhoncus vel iaculis iaculis, vestibulum non felis. Quisque pulvinar rhoncus orci eu pulvinar. Nulla nec massa viverra, malesuada ipsum et, vehicula odio. Integer nec efficitur risus. Maecenas eleifend placerat est, a lobortis lorem eleifend quis."
          + "Mauris et interdum tortor, eget blandit tortor. Cras et luctus justo. Praesent maximus scelerisque tellus vel condimentum. Nulla quam lorem, scelerisque eleifend tortor id, egestas lobortis sem. Quisque laoreet, leo et consequat sodales, dolor nibh pulvinar nisi, eu convallis nisl nisi pellentesque sem. Pellentesque gravida.";

        const string Message8K =
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis sem eget enim iaculis semper sit amet quis neque. Nullam aliquet quam at nulla tempus, sit amet rutrum sem ornare. Sed sed erat a ante accumsan dignissim. Ut neque nibh, porttitor nec enim ac, finibus mollis nisl. Morbi elit massa, consectetur quis dapibus id, mattis et mauris. Phasellus eget eros eget purus pellentesque facilisis a accumsan mi. Phasellus id tempus diam, et molestie lorem. Pellentesque pulvinar, ante at elementum tristique, enim dui finibus diam, in consectetur leo dolor eu lorem. Proin in scelerisque orci. Nam feugiat purus metus, vitae vestibulum lacus mollis eu. Curabitur blandit porttitor ornare. Phasellus eros nisi, mollis at hendrerit vel, auctor non ex. Nunc quis dignissim massa, eu ornare neque."
          + "Fusce diam elit, dignissim non egestas ut, laoreet quis purus. Donec scelerisque pharetra justo quis efficitur. Sed dignissim nulla ut purus feugiat efficitur. Donec quis libero consectetur, interdum dui eget, blandit urna. Maecenas imperdiet ipsum at egestas laoreet. Nunc sit amet elementum ligula. Fusce commodo eros tellus. Vestibulum tincidunt malesuada urna, id suscipit neque. Aliquam vestibulum fermentum orci, sed facilisis dui tincidunt mollis. Proin placerat convallis ex vitae auctor. Ut hendrerit elit sit amet ligula viverra interdum. Ut aliquet, ligula vel bibendum aliquam, ligula est volutpat arcu, eu interdum est metus non lacus. Donec ut quam sit amet mauris pretium semper. Quisque fermentum sem nec lectus fringilla euismod."
          + "Vivamus nec mi leo. Vivamus finibus in nibh non mattis. Nulla sodales euismod fringilla. Sed varius consectetur mi sed tincidunt. Nulla sed venenatis ex, ut iaculis elit. Aliquam feugiat malesuada diam at viverra. Vestibulum eget blandit massa. Nullam pharetra tincidunt libero varius rutrum. In nec est justo. Duis tempus ante non arcu condimentum imperdiet a a ante. Suspendisse nec laoreet libero. Quisque sed rhoncus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse bibendum, odio eu varius tempus, lacus odio scelerisque elit, et hendrerit arcu purus at nisi. Maecenas venenatis viverra eros ut sodales. Maecenas in laoreet mauris."
          + "Sed malesuada, nibh nec viverra laoreet, enim arcu pellentesque risus, vel accumsan urna felis condimentum nibh. Nullam ornare sapien a mauris ornare, sed vestibulum magna suscipit. Nulla quis fermentum augue. Donec nunc ante, placerat sit amet enim congue, auctor commodo nunc. Donec euismod ante vel facilisis aliquam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla lorem dui, laoreet quis pulvinar quis, tempor vitae magna. In sed justo metus. Ut pharetra auctor rhoncus. Duis id suscipit mauris. Nulla vel ex risus. Pellentesque dictum neque quam, sit amet sodales magna vestibulum euismod. Nullam et velit at nibh aliquam porttitor. Aliquam erat volutpat. Morbi consequat magna nibh, sed efficitur libero facilisis a."
          + "Etiam tincidunt neque at pulvinar molestie. Vivamus vitae euismod lacus. Pellentesque commodo nibh non odio lobortis mattis. Suspendisse lacinia enim in elit pretium, et pharetra ante faucibus. Curabitur scelerisque ipsum id dolor interdum hendrerit. Nam eu maximus orci, ut aliquet lacus. Proin dictum augue sed nulla rhoncus, in ullamcorper nibh dapibus. Praesent quam ipsum, commodo eu diam quis, maximus molestie nulla. Ut vel posuere libero, sit amet bibendum libero. Duis tristique libero ac felis condimentum, nec pellentesque nisl gravida."
          + "Sed a sodales turpis. Nam eget dui in sapien tempor malesuada ac sit amet libero. Nulla vitae augue enim. Donec feugiat rutrum purus id porttitor. Morbi at dolor arcu. Phasellus dignissim, eros ut rhoncus fermentum, ipsum felis semper orci, vehicula condimentum ligula tellus vel risus. Maecenas porttitor fermentum varius. Praesent dignissim est a mauris semper, ut volutpat mauris interdum. Nullam dictum ut est nec consectetur."
          + "Aliquam ante sapien, aliquet ultrices nibh vel, tincidunt pretium felis. Aliquam pellentesque velit nibh, volutpat pulvinar velit commodo sit amet. Quisque a tellus tempus, condimentum ligula nec, maximus quam. Phasellus suscipit mollis sem at dapibus. Nullam vehicula ante id cursus laoreet. Nunc venenatis vulputate dictum. In porttitor vulputate nunc id placerat. Maecenas aliquet in ante scelerisque volutpat. Morbi vitae pretium nisi. Pellentesque egestas, ante eu suscipit malesuada, lorem nibh luctus nisl, sed accumsan nibh dui lobortis orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum dignissim feugiat augue, dapibus congue nunc blandit nec."
          + "Phasellus suscipit lacus et purus imperdiet, vel aliquam velit finibus. Proin vel dui in dui pretium accumsan id et sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras nec ultrices ligula. Nulla dictum non arcu id laoreet. Pellentesque sollicitudin ligula massa, a placerat mauris egestas sit amet. Praesent at dictum arcu. Morbi arcu neque, blandit sit amet feugiat ullamcorper, ornare sed turpis. Aliquam vestibulum bibendum tellus nec interdum. Nam convallis libero dui, eu viverra est suscipit et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque pharetra felis massa, at dictum tortor sollicitudin ac. Curabitur vel eros ut quam ullamcorper porttitor."
          + "Phasellus non neque neque. Quisque in pulvinar ante. Donec non nulla ut quam condimentum dignissim nec a lacus. Nullam velit quam, porta porttitor sollicitudin vel, varius et libero. Etiam dui ligula, consectetur et massa molestie, ullamcorper viverra risus. Duis eget metus iaculis, facilisis ipsum vitae, dictum ante. Etiam ac auctor nunc. Integer hendrerit consectetur urna eget tristique. Phasellus at feugiat mi, eu faucibus arcu. Pellentesque vehicula sagittis convallis. Nam vitae mi ac sem feugiat venenatis. Proin pulvinar sed justo posuere fringilla."
          + "Aliquam erat volutpat. Donec pretium gravida dapibus. Duis diam leo, interdum non placerat et, euismod at arcu. Vestibulum eu ligula vitae mauris vehicula aliquam vitae et nulla. Phasellus sit amet tortor non sem semper maximus. Integer eu elementum ipsum. Sed magna magna, pulvinar et felis eget, euismod commodo enim. Nunc dolor tortor, facilisis non dolor eget, mattis fermentum lectus. Sed lacinia, velit quis egestas vulputate, leo diam congue nibh, ut scelerisque est dui non augue. Curabitur ut lacinia massa, nec ullamcorper augue. Nam consectetur consectetur lacus a porta. In a velit rhoncus, faucibus diam sit amet, rutrum magna. Proin semper ex arcu, ac pharetra odio lobortis in. Nam non magna quis nibh elementum fermentum. Etiam non tempor nisl."
          + "Nunc gravida pretium porttitor. Sed vitae arcu id nunc dictum vehicula sit amet eu eros. Nunc at urna a diam tristique tempor. Integer ut risus et elit rutrum dignissim. Nam sit amet turpis lectus. Sed pretium orci nec tortor gravida, ac rhoncus ex pretium. Proin volutpat tortor lectus, nec elementum justo porttitor sit amet. Aenean sit amet vestibulum elit. Integer vulputate tellus sed nibh malesuada efficitur. Vestibulum commodo neque eu urna suscipit interdum."
          + "Quisque consectetur vitae tellus eu auctor. Sed sagittis suscipit neque. Cras eu lectus nisi. Fusce a vestibulum lacus, nec feugiat tortor. Nullam accumsan varius justo nec aliquam. Vestibulum ac diam id lectus varius vehicula. Donec ac turpis vestibulum, convallis arcu a, congue purus. Pellentesque tincidunt diam nec lacus dictum consequat. Fusce consequat arcu ipsum, a consectetur mi ultrices sed. Fusce lobortis est lorem, at ultricies tortor efficitur eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris maximus posuere odio sed aliquam. Duis lacinia, nulla et iaculis elementum, sem velit volutpat ligula, sed aliquam elit ipsum faucibus orci. Donec nisi sem, sagittis id ex eget, tempus malesuada quam. Praesent sapien felis, placerat sed mollis sed, laoreet sit amet lectus. Donec in lorem vitae diam tempor pretium sit.";

    }

}